### ISSUE TITLE
Test failure: test_method.rb:810

### ISSUE THREAD

**Issue by wks** [mmtk/ruby#73]
It happened in the CI when running btest, using StickyImmix, debug build.  https://github.com/mmtk/mmtk-ruby/actions/runs/9679567454/job/26705823025?pr=79

log:

```
     [2024-06-26T12:30:17Z INFO  mmtk::memory_manager] Initialized MMTk with StickyImmix (DynamicHeapSize(1048576, 13405873760))
     [2024-06-26T12:30:17Z INFO  mmtk::util::heap::gc_trigger] [POLL] immix: Triggering collection (625/256 pages)
     [2024-06-26T12:30:17Z INFO  mmtk::plan::sticky::immix::global] Nursery GC
     [2024-06-26T12:30:17Z WARN  mmtk::util::heap::gc_trigger] Proportional nursery with min size 0.25 (262144) is smaller than DEFAULT_MIN_NURSERY (2097152). Use DEFAULT_MIN_NURSERY instead.
     [2024-06-26T12:30:17Z INFO  mmtk::scheduler::scheduler] End of GC (611/256 pages, took 55 ms)
     [2024-06-26T12:30:17Z INFO  mmtk::util::heap::gc_trigger] [POLL] immix: Triggering collection (625/256 pages)
     [2024-06-26T12:30:17Z INFO  mmtk::plan::sticky::immix::global] Full heap GC
     [2024-06-26T12:30:17Z INFO  mmtk::policy::immix::defrag] Defrag: true
     [2024-06-26T12:30:17Z WARN  mmtk::util::heap::gc_trigger] Proportional nursery with min size 0.25 (262144) is smaller than DEFAULT_MIN_NURSERY (2097152). Use DEFAULT_MIN_NURSERY instead.
     [2024-06-26T12:30:17Z WARN  mmtk::util::heap::gc_trigger] Proportional nursery with min size 0.25 (1232896) is smaller than DEFAULT_MIN_NURSERY (2097152). Use DEFAULT_MIN_NURSERY instead.
     [2024-06-26T12:30:17Z INFO  mmtk::scheduler::scheduler] End of GC (611/1202 pages, took 69 ms)
     [2024-06-26T12:30:17Z INFO  mmtk::util::heap::gc_trigger] [POLL] immix: Triggering collection (1283/1202 pages)
     [2024-06-26T12:30:17Z INFO  mmtk::plan::sticky::immix::global] Nursery GC
     [2024-06-26T12:30:17Z WARN  mmtk::util::heap::gc_trigger] Proportional nursery with min size 0.25 (1232896) is smaller than DEFAULT_MIN_NURSERY (2097152). Use DEFAULT_MIN_NURSERY instead.
     [2024-06-26T12:30:17Z INFO  mmtk::scheduler::scheduler] End of GC (1003/1202 pages, took 26 ms)
     [2024-06-26T12:30:17Z INFO  mmtk::util::heap::gc_trigger] [POLL] immix: Triggering collection (1253/1202 pages)
     [2024-06-26T12:30:17Z INFO  mmtk::plan::sticky::immix::global] Full heap GC
     [2024-06-26T12:30:17Z INFO  mmtk::policy::immix::defrag] Defrag: true
     ERROR: An MMTk GC thread panicked.  This is a bug.
     panicked at src/scanning.rs:42:13:
     Destination is not an MMTk object. Src: 0x200fff6c4d0 dst: 0x200fff1a140
        0: mmtk_ruby::handle_gc_thread_panic
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/lib.rs:101:14
        1: mmtk_ruby::set_panic_hook::{{closure}}
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/lib.rs:130:13
        2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2029:9
        3: std::panicking::rust_panic_with_hook
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:785:13
        4: std::panicking::begin_panic_handler::{{closure}}
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:659:13
        5: std::sys_common::backtrace::__rust_end_short_backtrace
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:171:18
        6: rust_begin_unwind
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
        7: core::panicking::panic_fmt
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
        8: <mmtk_ruby::scanning::VMScanning as mmtk::vm::scanning::Scanning<mmtk_ruby::Ruby>>::scan_object_and_trace_edges::{{closure}}
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/scanning.rs:42:13
        9: mmtk_ruby::abi::ObjectClosure::c_function_registered
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/abi.rs:217:9
       10: rb_mmtk_call_object_closure
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../mmtk_support.c:503:12
       11: rb_mmtk_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../mmtk_support.c:576:40
       12: rb_gc_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../gc.c:7247:9
       13: rb_iseq_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../iseq.c:349:9
       14: rb_imemo_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../imemo.c:455:9
       15: gc_update_object_references
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../gc.c:10930:9
       16: rb_mmtk_update_object_references
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../gc.c:14904:5
       17: rb_mmtk_scan_object_ruby_style
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../mmtk_support.c:538:5
       18: <mmtk_ruby::scanning::VMScanning as mmtk::vm::scanning::Scanning<mmtk_ruby::Ruby>>::scan_object_and_trace_edges::{{closure}}
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/scanning.rs:59:17
       19: mmtk_ruby::abi::ObjectClosure::set_temporarily_and_run_code
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/abi.rs:201:22
       20: <mmtk_ruby::scanning::VMScanning as mmtk::vm::scanning::Scanning<mmtk_ruby::Ruby>>::scan_object_and_trace_edges
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/scanning.rs:56:9
       21: mmtk::scheduler::gc_work::ScanObjectsWork::do_work_common::{{closure}}
                  at /home/runner/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/f1c0592/src/scheduler/gc_work.rs:837:21
       22: <mmtk::scheduler::gc_work::ProcessEdgesWorkTracerContext<E> as mmtk::vm::scanning::ObjectTracerContext<<E as mmtk::scheduler::gc_work::ProcessEdgesWork>::VM>>::with_tracer
                  at /home/runner/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/f1c0592/src/scheduler/gc_work.rs:291:22
       23: mmtk::scheduler::gc_work::ScanObjectsWork::do_work_common
                  at /home/runner/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/f1c0592/src/scheduler/gc_work.rs:833:13
       24: <mmtk::scheduler::gc_work::PlanScanObjects<E,P> as mmtk::scheduler::work::GCWork<<E as mmtk::scheduler::gc_work::ProcessEdgesWork>::VM>>::do_work
                  at /home/runner/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/f1c0592/src/scheduler/gc_work.rs:1016:9
       25: mmtk::scheduler::work::GCWork::do_work_with_stat
                  at /home/runner/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/f1c0592/src/scheduler/work.rs:45:9
       26: mmtk::scheduler::worker::GCWorker<VM>::run
                  at /home/runner/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/f1c0592/src/scheduler/worker.rs:244:13
       27: mmtk::memory_manager::start_worker
                  at /home/runner/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/f1c0592/src/memory_manager.rs:492:5
       28: <mmtk_ruby::collection::VMCollection as mmtk::vm::collection::Collection<mmtk_ruby::Ruby>>::spawn_gc_thread::{{closure}}
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/collection.rs:54:21
       29: std::sys_common::backtrace::__rust_begin_short_backtrace
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:155:18
       30: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/thread/mod.rs:529:17
       31: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panic/unwind_safe.rs:272:9
       32: std::panicking::try::do_call
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
       33: __rust_try
       34: std::panicking::try
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
       35: std::panic::catch_unwind
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
       36: std::thread::Builder::spawn_unchecked_::{{closure}}
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/thread/mod.rs:528:30
       37: core::ops::function::FnOnce::call_once{{vtable.shim}}
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
       38: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
       39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
       40: std::sys::pal::unix::thread::Thread::new::thread_start
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys/pal/unix/thread.rs:108:17
       41: <unknown>
       42: <unknown>
  ........................
   ..............................................................................
   ..............................................................................
   ..............................................................................
   ..............................................................................
   .....................
  Finished in 211.74 sec
  
  Fiber count: 10000 (skipping)
  #1154 test_method.rb:810: 
     class C0; def m *args; [:C0_m, args]; end; end
     class C1 < C0; def m(m1, m2, o1=:o1, o2=:o2, *r, p1, p2); super; end; end
     ; C1.new.m(1,2,3,4)
    #=> "" (expected "[:C0_m, [1, 2, :o1, :o2, 3, 4]]")  
  FAIL 1/0 tests failed
  make: *** [uncommon.mk:899: yes-btest] Error 1
```

**Comment by wks** [comment]
This is likely the same bug as https://github.com/mmtk/mmtk-ruby/issues/106.  It happens in a full-heap defrag GC which may move objects.  And it happens when scanning iseq.
